Update cdm16 syntax highlighting
cdm-processors/cdm-devkit pull request #17
Opened 2023-02-10 16:26 UTC by NikitaTrTr

Update syntax highlighting of instructions, add cdm16 macros highlighting

2023-02-10 17:02 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(beq|bz|bnne|bnnz|bne|bnz|bneq|bhs|bcs|bnlo|bncc|blo|bcc|bnhs|bncs|bmi|bnpl|bpl|bnmi|bvs|bnvc|bvc|bnvs|bhi|bnlc|bls|bnhi|bge|bnlt|blt|bnge|bgt|bnle|ble|bngt|br|banything|btrue|bnfals
Remove dublicates

2023-02-10 17:03 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(run|else|if|fi|is|gt|lt|le|ge|mi|pl|eq|ne|z|nz|cs|cc|vs|vc|hi|lo|hs|ls|continue|wend|until|while|save|restore|stays|true|break|tst|clr|do|then|unique|first_item|item|last_item|bnls|
Remove `run`

2023-02-10 17:07 UTC, Intelix8996 requested changes
Need to resolve conversations

2023-02-11 05:30 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(beq|bz|bnne|bnnz|bne|bnz|bneq|bhs|bcs|bnlo|bncc|blo|bcc|bnhs|bncs|bmi|bnpl|bpl|bnmi|bvs|bnvc|bvc|bnvs|bhi|bnlc|bls|bnhi|bge|bnlt|blt|bnge|bgt|bnle|ble|bngt|br|banything|btrue|bnfals
`sub` is missing

2023-02-11 05:31 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(beq|bz|bnne|bnnz|bne|bnz|bneq|bhs|bcs|bnlo|bncc|blo|bcc|bnhs|bncs|bmi|bnpl|bpl|bnmi|bvs|bnvc|bvc|bnvs|bhi|bnlc|bls|bnhi|bge|bnlt|blt|bnge|bgt|bnle|ble|bngt|br|banything|btrue|bnfals
Remove `zero|trap|fexc|bad`

2023-02-11 05:31 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(beq|bz|bnne|bnnz|bne|bnz|bneq|bhs|bcs|bnlo|bncc|blo|bcc|bnhs|bncs|bmi|bnpl|bpl|bnmi|bvs|bnvc|bvc|bnvs|bhi|bnlc|bls|bnhi|bge|bnlt|blt|bnge|bgt|bnle|ble|bngt|br|banything|btrue|bnfals
Remove `es|ds`

2023-02-11 05:34 UTC, Intelix8996 commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(run|else|if|fi|is|gt|lt|le|ge|mi|pl|eq|ne|z|nz|cs|cc|vs|vc|hi|lo|hs|ls|continue|wend|until|while|save|restore|stays|true|break|tst|clr|do|then|unique|first_item|item|last_item|bnls|
Move `db` and `dw` to `directives`

2023-02-11 18:38 UTC, Intelix8996 commented
Add `ext` to instructions

2023-02-15 14:23 UTC, cjvth requested changes

2023-02-15 14:23 UTC, cjvth commented on vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
> +				"match": "\\b(asect|rsect|dc|ds|tplate|end|end.|macro|mpop|mpush|mend|define|db|dw)\\b"
Add `align` to directives

2023-02-17 17:43 UTC, Intelix8996 approved these changes

2023-02-17 17:45 UTC, cjvth approved these changes

2023-02-17 17:46 UTC, merged